import { Prose } from "../../components/docs/Prose";
import { CodeBlock } from "../../components/docs/CodeBlock";
import { Callout } from "../../components/docs/Callout";
import { DocsPageHeaderForRoute } from "../../components/docs/DocsPageHeader";
import { motion } from "framer-motion";
import { Shield, Lock, Key, AlertTriangle, ShieldCheck, Eye, Database, Users, Fingerprint, Ban } from "lucide-react";

const threatModel = [
    { vector: "Plaintext Exposure in Transit", severity: "Critical", mitigation: "All patient data is encrypted via @zama-fhe/sdk in the browser DOM before any RPC call. Ciphertexts are opaque byte arrays — even if a man-in-the-middle intercepts the transaction, they see only encrypted blobs. The Zama network public key ensures only the coprocessor can process them.", status: "Mitigated" },
    { vector: "On-Chain State Leakage", severity: "Critical", mitigation: "Health metrics are stored as `euint32` ciphertext handles in private mappings. Standard `eth_getStorageAt` calls return encrypted handles, not values. Decryption requires ACL-authorized EIP-712 signatures from the data owner's wallet.", status: "Mitigated" },
    { vector: "Sybil Attack (Fake Trials)", severity: "High", mitigation: "Trial creation is gated by `SponsorRegistry.isVerifiedSponsor()`. Only addresses explicitly allowlisted by the protocol admin multisig can publish trials. This prevents attackers from creating trials with extreme parameter bounds designed to deduce patient data.", status: "Mitigated" },
    { vector: "Malformed Ciphertext Injection", severity: "High", mitigation: "Every encrypted input includes a ZK validity proof (`inputProof`) generated by @zama-fhe/sdk. Registry contracts validate this proof on-chain via FHE precompile before storing any ciphertext handle. Invalid proofs cause immediate transaction revert.", status: "Mitigated" },
    { vector: "Cross-Contract Reentrancy", severity: "Medium", mitigation: "All contracts that interface with the `EligibilityEngine` during FHE evaluations use OpenZeppelin `ReentrancyGuard` modifiers. The `nonReentrant` modifier prevents recursive calls during computationally expensive FHE operations.", status: "Mitigated" },
    { vector: "Unauthorized Decryption", severity: "Critical", mitigation: "Ciphertext decryption is controlled by FHE ACL. `FHE.allow(handle, address)` grants decryption rights only to specific addresses. The `ConsentManager` enforces patient-signed EIP-712 tokens before any sponsor can request re-encryption through the Zama KMS.", status: "Mitigated" },
    { vector: "Sponsor Key Compromise", severity: "High", mitigation: "If a sponsor's private key is leaked, the attacker can read previously consented profiles. The `SponsorRegistry` admin can execute `emergencyRemoveSponsor()` to immediately terminate all trial activity. Time-locked consent tokens auto-expire.", status: "Partially Mitigated" },
    { vector: "Withdrawal Amount Staging Leakage", severity: "Medium", mitigation: "v0.9 stores pending withdraw amounts as `euint64` and emits only `sufficientHandle` at request time. Plaintext amounts appear only after KMS reveal at completion or public ETH exit. `ClaimInitiated` omits destination/nullifier. See Private withdrawals doc for honest limits on native ETH settlement.", status: "Mitigated" },
    { vector: "Relayer Mis-binding on Public Exit", severity: "Medium", mitigation: "EIP-712 `WithdrawAuthorization` binds owner, stealthRecipient, sufficientHandle, exitMode, nonce, and deadline. Contract rejects wrong recipient, expired auth, replayed nonces, and exit-mode tampering (PEX-* tests). Relayer cannot redirect funds to an unsigned address.", status: "Mitigated" },
    { vector: "Event Log Metadata Analysis", severity: "Low", mitigation: "MedVault events emit public structural metadata (trial ID, patient address, status enum) but never emit ciphertexts or health values. Withdraw/stake events omit amounts. An observer can see that an application or withdraw occurred but cannot read staged encrypted amounts from logs.", status: "Accepted Risk" },
];

const colorStyles: Record<string, { iconBg: string; iconText: string; cardBorder: string; cardBg: string }> = {
    teal: {
        iconBg: "bg-blue-100",
        iconText: "text-blue-600",
        cardBorder: "border-blue-200",
        cardBg: "bg-blue-50/50",
    },
    purple: {
        iconBg: "bg-purple-100",
        iconText: "text-purple-600",
        cardBorder: "border-purple-200",
        cardBg: "bg-purple-50/50",
    },
    blue: {
        iconBg: "bg-blue-100",
        iconText: "text-blue-600",
        cardBorder: "border-blue-200",
        cardBg: "bg-blue-50/50",
    },
    amber: {
        iconBg: "bg-amber-100",
        iconText: "text-amber-600",
        cardBorder: "border-amber-200",
        cardBg: "bg-amber-50/50",
    },
};

export function SecurityModelDoc() {
    return (
        <motion.div>
            <Prose className="max-w-none">
                <DocsPageHeaderForRoute />

                {/* Security Posture Summary */}
                <div className="my-12 p-8 border border-slate-200 rounded-3xl bg-emerald-500/5 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl -mr-20 -mt-20" />
                    <div className="relative z-10 flex flex-col md:flex-row items-center gap-8">
                        <div className="w-24 h-24 rounded-2xl bg-emerald-500 flex items-center justify-center shadow-lg shadow-emerald-500/20">
                            <ShieldCheck className="w-12 h-12 text-white" />
                        </div>
                        <div>
                            <h3 className="text-2xl font-bold text-slate-900 mt-0 mb-2">Strong technical privacy, honest limits</h3>
                            <p className="text-slate-600 m-0 leading-relaxed">
                                Patient health fields are encrypted before they reach the chain and are compared homomorphically in
                                <code> EligibilityEngine</code>. Plaintext vitals should exist only in the patient browser during
                                encrypt/decrypt. Registration can still link a wallet to a commitment, trial bounds in
                                <code> TrialManager</code> are public, and native ETH movements remain visible at settlement.
                            </p>
                        </div>
                    </div>
                </div>

                <hr className="my-12 border-slate-200" />

                <h2>I. Threat Model</h2>
                <p>
                    The following threat model identifies the primary attack vectors relevant to MedVault's FHE-based clinical trial architecture, their severity, and the corresponding mitigations deployed in the current contract set.
                </p>

                <div className="not-prose my-8 space-y-4">
                    {threatModel.map((t, i) => (
                        <motion.div
                            key={t.vector}
                            initial={{ opacity: 0, y: 10 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.05 }}
                            viewport={{ once: true }}
                            className="p-5 rounded-2xl border border-slate-200 bg-white shadow-sm"
                        >
                            <div className="flex items-start justify-between gap-4 mb-3">
                                <div className="flex items-center gap-3">
                                    <AlertTriangle className={`w-4 h-4 shrink-0 ${t.severity === "Critical" ? "text-rose-500" : t.severity === "High" ? "text-amber-500" : t.severity === "Medium" ? "text-blue-500" : "text-slate-400"}`} />
                                    <h4 className="font-bold text-slate-900 text-sm m-0">{t.vector}</h4>
                                </div>
                                <div className="flex gap-2 shrink-0">
                                    <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${t.severity === "Critical" ? "bg-rose-100 text-rose-700" : t.severity === "High" ? "bg-amber-100 text-amber-700" : t.severity === "Medium" ? "bg-blue-100 text-blue-700" : "bg-slate-100 text-slate-500"}`}>
                                        {t.severity}
                                    </span>
                                    <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${t.status === "Mitigated" ? "bg-emerald-100 text-emerald-700" : t.status === "Partially Mitigated" ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-500"}`}>
                                        {t.status}
                                    </span>
                                </div>
                            </div>
                            <p className="text-xs text-slate-600 leading-relaxed m-0">{t.mitigation}</p>
                        </motion.div>
                    ))}
                </div>

                <hr className="my-12 border-slate-200" />

                <h2>II. FHE Cryptographic Guarantees</h2>
                <p>
                    Fully Homomorphic Encryption (FHE) provides provable security guarantees rooted in the hardness of the <strong>Learning With Errors (LWE)</strong> problem — a lattice-based cryptographic assumption believed to be quantum-resistant.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 my-10 not-prose">
                    {[
                        { icon: <Lock className="w-5 h-5" />, title: "Semantic Security", desc: "No polynomial-time adversary can distinguish between encryptions of two different plaintexts with non-negligible advantage. Even if an attacker collects every ciphertext stored in MedVault's contract state, they cannot learn any information about the underlying health values.", color: "teal" },
                        { icon: <Eye className="w-5 h-5" />, title: "Circuit Privacy", desc: "The output ciphertext of a homomorphic computation does not reveal the circuit (function) that was evaluated. The encrypted eligibility score does not leak whether the patient passed or failed any individual health check — only the final aggregated result.", color: "purple" },
                        { icon: <Fingerprint className="w-5 h-5" />, title: "Forward Secrecy", desc: "Each encryption uses fresh randomness. Even if the same patient re-encrypts the same age value, the resulting ciphertext will be entirely different. This prevents correlation attacks across multiple registrations or profile updates.", color: "blue" },
                        { icon: <Ban className="w-5 h-5" />, title: "Post-Quantum Resistance", desc: "The Zama FHE cryptosystem is built on lattice-based assumptions (LWE/RLWE) which are believed to be resistant to quantum computer attacks. Unlike RSA or ECDSA, MedVault's encryption layer is not threatened by Shor's algorithm.", color: "amber" },
                    ].map(g => {
                        const styles = colorStyles[g.color];
                        return (
                        <div key={g.title} className={`p-6 rounded-2xl border ${styles.cardBorder} bg-white shadow-sm`}>
                            <div className={`p-2.5 rounded-xl ${styles.iconBg} ${styles.iconText} w-fit mb-3`}>
                                {g.icon}
                            </div>
                            <h4 className="font-bold text-slate-900 text-sm mb-2 mt-0">{g.title}</h4>
                            <p className="text-xs text-slate-600 leading-relaxed mb-0">{g.desc}</p>
                        </div>
                        );
                    })}
                </div>

                <hr className="my-12 border-slate-200" />

                <h2>III. Access Control Architecture</h2>
                <p>
                    MedVault employs a layered access control model combining Solidity-level modifiers, Zama's on-chain ACL system, and application-level role gating.
                </p>

                <div className="not-prose my-8 overflow-hidden rounded-2xl border border-slate-200 shadow-sm">
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b border-slate-200 bg-slate-50">
                                    <th className="text-left px-4 py-3 font-bold text-slate-700">Layer</th>
                                    <th className="text-left px-4 py-3 font-bold text-slate-700">Mechanism</th>
                                    <th className="text-left px-4 py-3 font-bold text-slate-700">Scope</th>
                                    <th className="text-left px-4 py-3 font-bold text-slate-700">Contracts Protected</th>
                                </tr>
                            </thead>
                            <tbody>
                                {[
                                    { layer: "Ownership", mechanism: "OpenZeppelin `Ownable` / `Ownable2Step`", scope: "Admin functions (add/remove sponsors, authorize loggers)", contracts: "SponsorRegistry, DataAccessLog" },
                                    { layer: "Role Gating", mechanism: "`isVerifiedSponsor()` cross-contract call", scope: "Trial creation, requirement publishing", contracts: "TrialManager" },
                                    { layer: "Reentrancy", mechanism: "OpenZeppelin `ReentrancyGuard`", scope: "All external functions interfacing with FHE compute", contracts: "MedVaultRegistry, EligibilityEngine, StakingManager" },
                                    { layer: "FHE ACL", mechanism: "`FHE.allow()` / `FHE.allowThis()`", scope: "Per-ciphertext decryption authorization", contracts: "All contracts storing euint types" },
                                    { layer: "Consent", mechanism: "EIP-712 signed viewing tokens", scope: "Patient-authorized decryption of match results", contracts: "ConsentManager" },
                                    { layer: "Input Validation", mechanism: "ZK input proofs from @zama-fhe/sdk", scope: "Prevent malformed ciphertext injection", contracts: "MedVaultRegistry, TrialManager" },
                                ].map((row, i) => (
                                    <tr key={row.layer} className={`border-b border-slate-100 ${i % 2 === 0 ? "bg-white" : "bg-slate-50/50"}`}>
                                        <td className="px-4 py-3 font-bold text-blue-600 text-xs">{row.layer}</td>
                                        <td className="px-4 py-3 font-mono text-xs text-slate-600">{row.mechanism}</td>
                                        <td className="px-4 py-3 text-xs text-slate-600">{row.scope}</td>
                                        <td className="px-4 py-3 text-xs text-slate-500">{row.contracts}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>

                <hr className="my-12 border-slate-200" />

                <h2>IV. Key Management Architecture</h2>
                <p>
                    MedVault's key management involves three distinct cryptographic key types, each serving a specific purpose in the encryption lifecycle.
                </p>

                <div className="not-prose space-y-4 my-8">
                    {[
                        { title: "Zama Network Public Key", desc: "A 2048-byte FHE bootstrapping key fetched once per session via an `eth_call` to the Zama precompile address. Used by `@zama-fhe/sdk` to generate valid ciphertexts that the coprocessor can process. This key is public — it enables encryption, not decryption.", icon: <Key className="w-5 h-5" />, color: "teal" },
                        { title: "EIP-712 Viewing Key (Re-encryption Token)", desc: "Generated per-user, per-contract by signing a structured EIP-712 message in MetaMask. This token authorizes the Zama KMS to perform threshold decryption of a specific ciphertext handle and return the plaintext exclusively to the token holder. Tokens can be time-scoped.", icon: <Fingerprint className="w-5 h-5" />, color: "purple" },
                        { title: "Zama KMS Threshold Shares", desc: "The decryption key for the FHE scheme is split across multiple Zama validator nodes using Shamir's Secret Sharing. No single node possesses the complete decryption key. A threshold (e.g., 3-of-5) of validators must collaborate to decrypt any ciphertext, preventing any single point of key compromise.", icon: <Users className="w-5 h-5" />, color: "amber" },
                    ].map(k => {
                        const styles = colorStyles[k.color];
                        return (
                        <div key={k.title} className={`p-5 rounded-2xl border ${styles.cardBorder} bg-white flex gap-4 items-start`}>
                            <div className={`p-2.5 rounded-xl ${styles.iconBg} ${styles.iconText} shrink-0`}>
                                {k.icon}
                            </div>
                            <div>
                                <h4 className="font-bold text-slate-900 text-sm mb-1 mt-0">{k.title}</h4>
                                <p className="text-xs text-slate-600 leading-relaxed mb-0">{k.desc}</p>
                            </div>
                        </div>
                        );
                    })}
                </div>

                <CodeBlock
                    filename="EIP-712 Viewing Key Generation Pattern"
                    language="typescript"
                    code={`// Generate a viewing key for a specific contract's ciphertext
const { token, publicKey } = await fhevmInstance.generateToken({
    verifyingContract: PATIENT_REGISTRY_ADDRESS,
    // The EIP-712 domain separator ensures this token
    // cannot be replayed against a different contract.
});

// Use the token to request decryption from the Zama KMS
const decryptedAge = await fhevmInstance.decrypt(
    PATIENT_REGISTRY_ADDRESS,
    token,
    encryptedAgeHandle  // The ciphertext handle stored on-chain
);
// decryptedAge is now a BigInt visible only to the patient`}
                />

                <Callout type="warning" title="Key Rotation & Revocation">
                    Currently, Zama's testnet does not support network key rotation. If the network public key were compromised (a theoretical scenario requiring breaking LWE), all ciphertexts encrypted with that key would be at risk. In production, MedVault would implement periodic key rotation with re-encryption of active ciphertext handles.
                </Callout>

                <hr className="my-12 border-slate-200" />

                <h2>V. Audit Readiness Checklist</h2>
                <p>
                    The following checklist summarizes MedVault's security posture for formal audit engagement:
                </p>

                <div className="not-prose my-8 rounded-2xl border border-slate-200 overflow-hidden shadow-sm divide-y divide-slate-100">
                    {[
                        "All contracts use Solidity 0.8.24+ with built-in overflow protection",
                        "OpenZeppelin Ownable and ReentrancyGuard applied to all state-changing functions",
                        "FHE.allow() ACL set explicitly for every ciphertext storage operation",
                        "ZK input proofs validated on-chain before storing any encrypted patient data",
                        "No encrypted types emitted in event logs (prevents ciphertext leakage)",
                        "SponsorRegistry admin-gated to prevent Sybil trial creation",
                        "DataAccessLog records every sensitive operation with anonymized hashes",
                        "100/100 test cases passing across EligibilityEngine, StakingManager, and Rewards",
                        "ConsentManager enforces EIP-712 signatures for all decryption requests",
                        "Emergency sponsor removal function available for key compromise response",
                    ].map((item, i) => (
                        <div key={i} className="flex items-center gap-4 px-5 py-3 bg-white hover:bg-slate-50 transition-colors">
                            <ShieldCheck className="w-4 h-4 text-emerald-500 shrink-0" />
                            <span className="text-sm text-slate-700">{item}</span>
                        </div>
                    ))}
                </div>

            </Prose>
        </motion.div>
    );
}
