/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MedVaultAutomationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkUpkeep"
      | "consentManager"
      | "engine"
      | "enqueue"
      | "enqueued"
      | "finalized"
      | "owner"
      | "performUpkeep"
      | "queue"
      | "setVault"
      | "trialManager"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AddedToQueue" | "TrialFinalized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consentManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "engine", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "enqueue",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enqueued",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "queue", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trialManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consentManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "engine", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enqueue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enqueued", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finalized", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "queue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "trialManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace AddedToQueueEvent {
  export type InputTuple = [patient: AddressLike, trialId: BigNumberish];
  export type OutputTuple = [patient: string, trialId: bigint];
  export interface OutputObject {
    patient: string;
    trialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrialFinalizedEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    distributed: boolean,
    deactivated: boolean
  ];
  export type OutputTuple = [
    trialId: bigint,
    distributed: boolean,
    deactivated: boolean
  ];
  export interface OutputObject {
    trialId: bigint;
    distributed: boolean;
    deactivated: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedVaultAutomation extends BaseContract {
  connect(runner?: ContractRunner | null): MedVaultAutomation;
  waitForDeployment(): Promise<this>;

  interface: MedVaultAutomationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;

  consentManager: TypedContractMethod<[], [string], "view">;

  engine: TypedContractMethod<[], [string], "view">;

  enqueue: TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  enqueued: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  finalized: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  performUpkeep: TypedContractMethod<
    [performData: BytesLike],
    [void],
    "nonpayable"
  >;

  queue: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { patient: string; trialId: bigint }],
    "view"
  >;

  setVault: TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;

  trialManager: TypedContractMethod<[], [string], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "consentManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "engine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "enqueue"
  ): TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enqueued"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalized"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[performData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "queue"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { patient: string; trialId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trialManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AddedToQueue"
  ): TypedContractEvent<
    AddedToQueueEvent.InputTuple,
    AddedToQueueEvent.OutputTuple,
    AddedToQueueEvent.OutputObject
  >;
  getEvent(
    key: "TrialFinalized"
  ): TypedContractEvent<
    TrialFinalizedEvent.InputTuple,
    TrialFinalizedEvent.OutputTuple,
    TrialFinalizedEvent.OutputObject
  >;

  filters: {
    "AddedToQueue(address,uint256)": TypedContractEvent<
      AddedToQueueEvent.InputTuple,
      AddedToQueueEvent.OutputTuple,
      AddedToQueueEvent.OutputObject
    >;
    AddedToQueue: TypedContractEvent<
      AddedToQueueEvent.InputTuple,
      AddedToQueueEvent.OutputTuple,
      AddedToQueueEvent.OutputObject
    >;

    "TrialFinalized(uint256,bool,bool)": TypedContractEvent<
      TrialFinalizedEvent.InputTuple,
      TrialFinalizedEvent.OutputTuple,
      TrialFinalizedEvent.OutputObject
    >;
    TrialFinalized: TypedContractEvent<
      TrialFinalizedEvent.InputTuple,
      TrialFinalizedEvent.OutputTuple,
      TrialFinalizedEvent.OutputObject
    >;
  };
}
